#A simple calculator project, you can this as your first python project.

print("Hello!")
print("This is a simple and a basic calculator.")
print("\n")
a = int(input("Please Enter the first number : "))
print("\n")
b = int(input("Please Enter the second number : "))
print("\n")
print("The sum of ", a, "and", b, "is : ", a + b)
print("\n")
print("The difference of ", a, "and", b, "is : ", a - b)
print("\n")
print("The product of ", a, "and", b, "is : ", a * b)
print("\n")
print("The result after dividing ", a, "by", b, "is : ", (a / b))
print("\n")
